name:                hw-json-simd
version:             0.1.0.0
github:              "haskell-works/hw-json-simd"
license:             BSD3
author:              "John Ky"
maintainer:          "newhoggy@gmail.com"
copyright:           "2018 John Ky"

extra-source-files:
- cbits/simd.h
- cbits/simd-spliced.c
- cbits/simd-state.c
- cbits/simd-phi-table-32.c
- cbits/simd-transition-table-32.c
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/haskell-works/hw-json-simd#readme>

ghc-options: -Wall

dependencies:
- base >= 4.7 && < 5
- binary
- bits-extra
- bytestring
- hw-bits
- hw-prim
- lens
- parallel
- mmap
- prettyprinter
- split
- text
- vector
- word8

library:
  build-tools:
  - c2hs
  c-sources:
  - cbits/debug.c
  - cbits/simd-spliced.c
  - cbits/simd-state.c
  - cbits/simd-phi-table-32.c
  - cbits/simd-transition-table-32.c
  include-dirs:
  - cbits
  source-dirs: src
  cc-options: -mssse3 -O3 -mlzcnt -mbmi2 -mavx2

executables:
  hw-json-simd-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw-json-simd
    - optparse-applicative

tests:
  hw-json-simd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw-json-simd

when:
- condition: flag(sse42)
  cc-options:
  - -msse4.2
  ghc-options:
  - -msse4.2
- condition: flag(bmi2)
  cc-options:
  - -mbmi2
  - -DBMI2_ENABLED
- condition: (flag(bmi2)) && (impl(ghc >=8.4.1))
  ghc-options:
  - -mbmi2
  - -msse4.2
- condition:  flag(avx2)
  cc-options:
  - -mavx2
  - -DAVX2_ENABLED
- condition: (flag(avx2)) && (impl(ghc >=8.4.1))
  ghc-options:
  - -mbmi2
  - -msse4.2
  cpp-options:
  - -DBMI2_ENABLED
  - -DAVX2_ENABLED
- condition: (impl(ghc >=8.0.1))
  ghc-options:
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
- condition: (!impl(ghc >=8.0.1))
  dependencies:
    - transformers          >= 0.4        && < 0.6
    - semigroups            >= 0.8.4      && < 0.19

flags:
  sse42:
    description: Enable SSE 4.2 optimisations.
    manual: false
    default: true

  bmi2:
    description: Enable bmi2 instruction set
    manual: false
    default: false

  avx2:
    description: Enable avx2 instruction set
    manual: false
    default: false
