name:                hw-json-simd
version:             0.1.0.0
github:              "githubuser/hw-json-simd"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- src/cbits/font_load.h
- src/cbits/font_load.c
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hw-json-simd#readme>

dependencies:
- base >= 4.7 && < 5

library:
  build-tools:
  - c2hs
  c-sources:
  - cbits/simd.c
  include-dirs:
  - cbits
  source-dirs: src

executables:
  hw-json-simd-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw-json-simd

tests:
  hw-json-simd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw-json-simd
